package com.auto.code.generator.specification;

import javax.validation.constraints.NotBlank;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * @author Anshu Mishra
 *
 */
public class GeneralSpecification {
	@JsonProperty(value = "project", required = true)
	private String project;
	@NotBlank
	private String basePackageName;
	@NotBlank
	private String rootPath;
	@NotBlank
	private ApiSpecification apiSpecification;
	private String autoGeneratedFilePath;

	public String getBasePackageName() {
		return basePackageName;
	}

	public void setBasePackageName(String basePackageName) {
		this.basePackageName = basePackageName;
	}

	public String getRootPath() {
		return rootPath;
	}

	public void setRootPath(String rootPath) {
		this.rootPath = rootPath;
	}

	public String getProject() {
		return project;
	}

	public void setProject(String project) {
		this.project = project;
	}

	public String getAutoGeneratedFilePath() {
		return autoGeneratedFilePath;
	}

	public void setAutoGeneratedFilePath(String autoGeneratedFilePath) {
		this.autoGeneratedFilePath = autoGeneratedFilePath;
	}

	public ApiSpecification getApiSpecification() {
		return apiSpecification;
	}

	public void setApiSpecification(ApiSpecification apiSpecification) {
		this.apiSpecification = apiSpecification;
	}

}
