package com.auto.code.generator.core;

import com.auto.code.generator.specification.ApiSpecification;
import com.sun.codemodel.JCodeModel;

/**
 * @author Anshu Mishra
 *
 */
public class RequestGenerator extends BaseDomainGenerator {

	public void generateRequest(JCodeModel codeModel, ApiSpecification specification, String basePackage,
			String autoGeneRatedFilePath) throws Exception {
		if (specification != null && specification.getApiRequest() != null) {
			String className = specification.getApiName() + "Request";
			generateCore(codeModel, className, specification.getApiRequest().getFields(), basePackage, specification,
					autoGeneRatedFilePath);

		}

	}

}
